name: multi jobs

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: First job
          run: echo "First job"
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: second job
          run: echo "second job"